### PR TITLE
refactor/1916 - Update KORD

### LINKED ISSUE #1916: Revive ORD - Chicago O'Hare
Reviving ORD, Chicago O'Hare.

### PR DESCRIPTION
**Pull request by MichaelDMcCracken**
Resolves #1916 

The purpose of this pull request is to add ORD.

### CODE REVIEW

**Review by Fechulo — CHANGES_REQUESTED** [review]
Ah this file brings back memories 😍 
Github won't let me add review comments on the file itself because it's too large so:
ERNNY7: Missing restrictions at KOHLL and CHDRR
MADII6: (phonetic) name is wrong
VEECK5: VEECK is entered twice, once in the BONNT transition and then again in the body
WYNDE2: UFDUH transition is named incorrectly. Also missing restrictions at TVC and UFDUH
Misc.: Could we add the extended centerline for 28L, given that it is used as an arrival runway by default?

**Comment by MichaelDMcCracken** [comment]
>  Could we add the extended centerline for 28L, given that it is used as an arrival runway by default?

How do I do that?

**Comment by MichaelDMcCracken** [comment]
- [x] ERNNY7: Missing restrictions at KOHLL and CHDRR
- [x] MADII6: (phonetic) name is wrong
- [x] VEECK5: VEECK is entered twice, once in the BONNT transition and then again in the body
- [X] WYNDE2: UFDUH transition is named incorrectly.
- [X] Also missing restrictions at TVC and UFDUH
- [ ] Could we add the extended centerline for 28L, given that it is used as an arrival runway by default?

**Comment by MichaelDMcCracken** [comment]
@Fechulo @erikquinn 
What does the `sepFromAdjacent` property actually do? I tried setting this to `0` for all of the runways in hopes that it would allows simultaneous parallel approaches but it didn't work.

**Comment by MichaelDMcCracken** [comment]
@Fechulo anything happening with this pull?

**Review by Fechulo — APPROVED** [review]

**Pull request merged**
