### PR TITLE
documentation/1972 - Updated scoring file to reflect current implementation

### LINKED ISSUE #1972: Undocumented loss of points when flying in restricted areas
Browser: Any

Airport: `KDCA`

Approximate play time before issue: Any

#### Issue Description
When an airctaft is flown into a restricted area, the player loses 200 points. This is not documented in [scoring.md](/openscope/openscope/blob/develop/documentation/scoring.md).

#### Steps to reproduce
- Fly any plane into a restricted area
- Observe score go down by 200

### PR DESCRIPTION
**Pull request by farid-fari**
Resolves #1972

The purpose of this pull request is to correct documentation on scoring to reflect current reality.

### CODE REVIEW

**Review by n8rzz — APPROVED** [review]
Great work here and thank you for the PR! If the strikethrough bits are no longer valid, we can remove them.

**Comment by farid-fari** [comment]
I wasn't sure if I should remove them or if they were there because they were goals that haven't been implemented yet... Let me know if I should just delete them.

**Comment by erikquinn** [comment]
I suppose this is fine, but it is worth pointing out #1020 😛 

Will merge the update in a bit anyway, since we might as well after you did the work anyway :)

**Comment by farid-fari** [comment]
I don't really care much about scores either, but it's useful to see at a glance if you're doing something majorly wrong without realizing (e.g. restricted areas). Also super useful for debugging maps when you're creating them ;)

**Pull request merged**
