### PR TITLE
refactor/242 - Overhaul KJFK

### LINKED ISSUE #242: Airport Revival: John F. Kennedy International Airport
John F. Kennedy International Airport (IATA: JFK, ICAO: KJFK, FAA LID: JFK) is a major international airport located near South Ozone Park in the borough of Queens in New York City, United States, 12 miles (20 km) southeast of Lower Manhattan. It is the busiest international air passenger gateway into the United States,  the fifth busiest airport in the United States and the busiest airport in the New York City airport system, handling 58,956,288 passengers in 2016. Over ninety airlines operate out of the airport, with non-stop or direct flights to destinations in all six inhabited continents. The airport features six passenger terminals and four runways. It serves as a hub for American Airlines and Delta Air Lines and is the primary operating base for JetBlue Airways. In the past, JFK served as a hub for Eastern, National, Pan Am, and TWA.

Opened as New York International Airport in 1948, it was commonly known as Idlewild Airport before being renamed in 1963 in memory of John F. Kennedy, the 35th President of the United States, following his assassination.

This airport was omitted when spawnPatterns were introduced.

### PR DESCRIPTION
**Pull request by erikquinn**
Resolves #242.

### Completion Checklist
- [ ] terrain file
- [ ] polygonal airspace boundary
- [ ] all SIDs
- [ ] all STARs
- [ ] information to validate traffic levels
- [ ] base video map
- [ ] no console errors or warnings

---

Bring KJFK up to date with the latest changes so it can be brought back into the game.

### CODE REVIEW

**Comment by headphase** [comment]
Quick update: Still working on spawn patterns.  All traffic will be based on a detailed analysis of real life flight info with airline frequency, aircraft type, and correct departure/arrival corridors taken into account.  Arrivals nearly complete. Haven't begun departures yet.  This update naturally requires each airline operating at JFK to be reviewed for proper fleet type and count, so the pr will include a large list of updated airlines as well as a number of brand new airlines to the game.  All airline info is sourced from cited Wikipedia entries.

**Comment by headphase** [comment]
Sorry for the slow pace; arrivals are all complete including the major domestic airlines and their regionals.  Just need to take care of the departures and button some loose ends.

**Comment by erikquinn** [comment]
Being worked from branch `feature/242-A`...

**Comment by erikquinn** [comment]
Too many conflicts to reasonably resolve. Replaced with #1460. Closing in favor of that newer PR.

**Pull request closed without merging**
