### PR TITLE
Enhancement/2030 - add support for system command aliases, implement 'tw' alias for 'timewarp'

### LINKED ISSUE #2030: Add support for system command aliases, implement 'tw' alias for 'timewarp'
`tw` as an alias for `timewarp` doesn't actually work because the pipeline for handling system commands doesn't check for aliases.

https://github.com/openscope/openscope/blob/2860a23834ec11311cea47bac199031d0844955b/src/assets/scripts/client/commands/aircraftCommand/aircraftCommandMap.js#L212-L216

### PR DESCRIPTION
**Pull request by cake-pie**
Resolves #2030

The purpose of this pull request is to add support for system command aliases so that the alias `tw` for `timewarp` actually works.

### CODE REVIEW

**Review by n8rzz — APPROVED** [review]
Only thing missing here are some tests, but I don't remember if we even have tests for the system commands. If we do, are there any we could add for this? If we don't, nothing to worry about for now.

The work you've done here looks wonderful, thank you for your contribution!

**Comment by cake-pie** [comment]
Looked at the existing tests related to system commands, found two relevant ones. In those, only one out of the four system commands in documentation was being fed as test case, so I added the other three. Added new tests for system command aliases to ensure they produce the same outcome as the root command.

**Review by n8rzz — APPROVED** [review]
Hell yeah! Nice work!! :shipit:

**Comment by erikquinn** [comment]
@cake-pie oh thank god for this one. So overdue 😄 

Thank you! :)

**Pull request merged**
