### PR TITLE
enhancement/1644 - Add KBWI

### LINKED ISSUE #1644: Add KBWI
While we have both KIAD and KDCA, KBWI is the airport in the Baltimore/Washington region with the most passengers, (and it's also my home airport) so I think adding it might be a good thing to do! While we mostly get Southwest 737s and smaller jets, we also get a lot of cargo 767s, a 757 every once in a while, and British airways service. I'm going to get started on this, but I'd appreciate help. FlapsNSlats#7791 on Discord.

### PR DESCRIPTION
**Pull request by MarylandFlyer**
Resolves #1644 

The purpose of this pull request is to add Baltimore-Washington Intl Airport (KBWI).

### CODE REVIEW

**Comment by Hawaiicoder** [comment]
I think I know why the test is failing (trailing comma in the fix list), but I'm not going to bother fixing it until I complete my fixes.

**Comment by Hawaiicoder** [comment]
I still have to do a ton of work but I'm happy with how it's progressing.

**Comment by Hawaiicoder** [comment]
Progress will be minimal until approx. September 10th.

**Comment by Hawaiicoder** [comment]
Work resumes tomorrow.

**Comment by Hawaiicoder** [comment]
Sorry for the lack of progress. I expect to have this done by Christmas.

**Comment by Hawaiicoder** [comment]
Ok, after a long break, I'm going to get back to work on this!

**Comment by Hawaiicoder** [comment]
Forgive this probably ignorant question- could someone explain what the conflict is and what I can do? If I can’t do something, can someone else deconflict the conflicting files?

**Comment by cake-pie** [comment]
(Apologies if I state things you already know, just trying to be thorough, )

#1726 (10 days ago) replaced `airportLoadList.js` with `airportLoadList.json`. Because your feature branch includes edits to `airportLoadList.js` (which no longer exists on `develop`) git isn't quite smart enough to figure out what to do automatically, and that conflict needed to be fixed manually to bring your feature branch in line with the latest `develop`.

In an attempt to resolve that, you created your own `airportLoadList.json` in a separate commit (4fb57bd) rather than updating your feature branch via a merge or rebase, thus exacerbating the problem.

Here are steps to fix.

1. `git checkout develop`
switch to your local copy of develop branch
1. `git pull openscope develop`
make sure it is up to date with the repo before we continue
(if your remotes aren't set so `openscope` points to this repo, holler and I'll assist further)
1. `git checkout Hawaiicoder-patch-1-1`
switch to your local copy of this feature branch.
1. `git checkout -b enhancement/1644`
make a new branch from this point. We'll take this opportunity to follow [branch name conventions](https://github.com/openscope/openscope/blob/develop/CONTRIBUTING.md#creating-a-pull-request).
leave the original branch as a backup for now (normally, we'd make the new branch for backup purposes and fix the original)
1. You should be on branch `enhancement/1644`
1. `git rebase -i develop`
We're doing a rebase, i.e. taking your changes, and "replay" them with the current up-to-date `develop` branch as the starting point, rather than the `develop` of several months ago when you first started working on this.
The `-i` switch makes the process interactive so we can pick and choose what will happen. Your text editor will open with a list of your commits:
```
pick c0dc012d3 Add KBWI via upload
pick 66a195873 Add files via upload
pick e0087d294 Add KBWI terrain files
pick f0e2e3659 Update KBWI.json to add fixes
pick 765bcf7c9 Add more fixes, remove trailing comma.
pick def270e71 Update airportLoadList.js
pick 784d1bbba Debug airportLoadList.js
pick 8e933e1e7 Add runways
pick 6d2e157ea Update so video map will now show.
pick b16d316cb Fix RWY 10/28 and overlapped fixes.
pick abe92f7da Remove comma
pick 1b8eaca55 Add fixes
pick 78aabb5e7 Final update to fix list!
pick 9772c62aa Add files via upload
pick 15c4716dc Add Contour Airlines
pick ff1f20df3 Remove VTE
pick 4fb57bda7 Update airportLoadList
pick 8fc9dd19d Update airportLoadList.js
```
7. We're now going to discard some of the commits.
Edit the file as follows, replacing `pick` with `d` (short for `drop`). I've also added comments to explain each one but you don't have to put those comments in the file.
```
pick c0dc012d3 Add KBWI via upload
pick 66a195873 Add files via upload
pick e0087d294 Add KBWI terrain files
pick f0e2e3659 Update KBWI.json to add fixes
pick 765bcf7c9 Add more fixes, remove trailing comma.
d def270e71 Update airportLoadList.js  // } modifies file that no longer exists
d 784d1bbba Debug airportLoadList.js   // }
pick 8e933e1e7 Add runways
pick 6d2e157ea Update so video map will now show.
pick b16d316cb Fix RWY 10/28 and overlapped fixes.
pick abe92f7da Remove comma
pick 1b8eaca55 Add fixes
pick 78aabb5e7 Final update to fix list!
pick 9772c62aa Add files via upload
d 15c4716dc Add Contour Airlines  // } these two cancel each other out, basically redundant
d ff1f20df3 Remove VTE            // }
d 4fb57bda7 Update airportLoadList     // } these attempts don't fix the conflict
d 8fc9dd19d Update airportLoadList.js  // }
```
8. Save and close the file. git should start working on the rebase according to the instructions we've just set.
1. Once done you should see a message like `Successfully rebased and updated ...`
(The branch should now be 12 commits ahead of `develop`)
1. The changes to `airportLoadList.js` have been thrown away, so you will need to redo them, except it'll be in `airportLoadList.json` this time. commit those changes.
1. `git push -u openscope enhancement/1644`
push the new, fixed branch to the repo.
(if the branch name didn't need fixing, we'd be doing a force push (`git push -f`) here instead)
1. make a new PR with the new branch, and close this PR in favor of the new one
1. once sure everything is in order and you don't need the backup copy anymore, delete the backup branch locally
`git branch -D Hawaiicoder-patch-1-1`
and also correspondingly on this repo via https://github.com/openscope/openscope/branches (hit that trash can button)

**Comment by Hawaiicoder** [comment]
@cake-pie It works- up to step 8. It then generates an error for each commit line, for instance: error: could not parse '8fc9dd19d'
error: invalid line 20: d 8fc9dd19d Update airportLoadList.js  // }
I'm probably doing something wrong, but being new to git, I have no clue what it is.

**Comment by cake-pie** [comment]
That's *very* odd. An error for each of all 18 commits, or only the 6 lines that were edited?
Did you edit the  6 lines by hand, or did you just copy and paste everything from my post, replacing the original file wholesale?

---

Assuming you haven't done anything else since encountering the error:

`git rebase --abort` if you haven't already done so.

That should put you back on branch `enhancement/1644`

Do `git pull openscope Hawaiicoder-patch-1-1` and verify that it you see the following output

```
From https://github.com/openscope/openscope
 * branch                Hawaiicoder-patch-1-1 -> FETCH_HEAD
Already up-to-date.
```

That'll help verify that things on your end are "as expected" before we continue troubleshooting

**Comment by Hawaiicoder** [comment]
Error was for all 18 commits. It also seems not to believe that Hawaiicoder-patch-1-1 is real.

**Comment by Hawaiicoder** [comment]
image
image
image
image
image

**Comment by cake-pie** [comment]
Oh. okay, that was definitely not what I expected.

Just to confirm, have you been doing all your editing via the github website?

**Comment by Hawaiicoder** [comment]
Editing files in Visual Studio Code, commits via the website.

**Comment by cake-pie** [comment]
Alright, my bad for incorrectly assuming you were using a local clone of the repo. :pray: 
Looks like what you have there is from when you first made your own fork on github, and then cloned that locally -- but you've most likely not actually used it, considering you've been committing changes via github website.

To clean up locally on your machine (due to attempts at following my instructions above):
1. `git add .`
2. `git reset --hard`
3. `git checkout develop`
4. `git branch -d enhancement/1644`

That'll leave you with just the `develop` branch locally.

I'll fix the merge conflict for you in a bit, then you can resume from there.

**Comment by Hawaiicoder** [comment]
Thank you. I'm definitely still a beginner, but with all the documentation available, I'm definitely learning. Little things like this get me all the time, though!

**Comment by cake-pie** [comment]
No probs. Merge conflict dealt with. You'll still need to (re)add the airport to `airportLoadList.json`, and then should be able to pick up from where you left off.

**Comment by Hawaiicoder** [comment]
That won't cause a conflict, correct?

**Comment by cake-pie** [comment]
Nope, it shouldn't.

**Comment by Hawaiicoder** [comment]
Hey! Sorry for the lack of progress here. I don't understand how to build SIDs/STARs. I can't figure it out, and I'm wondering if A) someone can write up a better explanation than that in the documentation or B) just do it for me (I know it's a lot to ask and you definitely don't have to do it). Here's the document I've been using for the procedures: https://flightaware.com/resources/airport/KBWI/ALL/all/pdf
Thanks in advance for your help!!

**Comment by Fechulo** [comment]
My suggestion would be to check another airport's file and compare to the charts. You'll get a good idea of what everything means that way. If you have any specific questions feel free to ask on slack

**Comment by Hawaiicoder** [comment]
Here's a dumb question (would ask in Slack but it's blocked for me)- can I specify an altitude as a fix with no fix/VOR/DME? BWI has a few procedures and they involve a climb to a certain altitude (no specified fix or DME) before the initial turn. Thanks!

**Comment by Hawaiicoder** [comment]
Hey all. It's been over a year since I started this project. I certainly enjoyed the process, but it was much, much more demanding than I first anticipated. As things stand at the moment, I don't have the time and I haven't for a while. I'm not going to close this PR because I hope that someone will be able to carry on with this project, but I'm afraid that by this point much of my work may be outdated. I'll try to start doing little bits here and there in hopes of getting this done one day. Hopefully at the very least my work so far provides a framework for someone else to finish this off.

**Pull request closed without merging**
