### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
Hi, I'm making updates for Open Collective. Either you or a supporter signed this repo up for Open Collective. This pull request adds backers and sponsors from your Open Collective https://opencollective.com/openscope ❤️
  
  It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]. See how it looks on [this repo](https://github.com/apex/apex#backers).
We have also added a `postinstall` script to let people know after `npm|yarn install` that you are welcoming donations (optional). [[More info](https://github.com/OpenCollective/opencollective-cli)]
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets

  P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the placeholders on the README because we believe it's important to acknowledge the people in your community that are contributing (financially or with code!).

  Thank you for your great contribution to the open source community. You are awesome! 🙌
  And welcome to the open collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other open source sustainers!

### CODE REVIEW

**Comment by monkeywithacupcake** [comment]
Sorry, I read that you don't do forks. However, this is an external change, not to actual features. 
Also, your open collective only has custom tiers, so I will need to come back and update the badges and images after I  figure out what the actual tier slugs are. (since they are not backers and sponsors (default)). Cheers!

**Comment by n8rzz** [comment]
Please see https://github.com/openscope/openscope/blob/develop/documentation/git-flow-process.md for project conventions on git branching strategy.

New features (like this one) should be branched off of `develop` and a PR should also target `develop`.  

As it stands, this diff is way to large to offer any feedback here.

**Comment by erikquinn** [comment]
@monkeywithacupcake Good evening!!! Is it just these two commits that need to be added?

image

Also, could I get some contact info for you (slack? or even email or something)? I have a few brief questions you may be able to help with in regards to getting that fully configured to our liking. Thank you! 😃

**Comment by monkeywithacupcake** [comment]
Yes @erikquinn - Come chat with us in the #opensource channel on https://slack.opencollective.com (I'm @jess in the opencollective slack)

**Comment by erikquinn** [comment]
Will be going a different direction with this. Closing.

**Pull request closed without merging**
