### PR TITLE
devops/1137 - Update project dependencies

### LINKED ISSUE #1137: Update project dependencies
Its been some time since we've updated our libraries, which is like a lifetime in JS.

Things we should update/add:
- [x] node reference in `package.json`
- [x] npm reference in `package.json`
- [x] babel and supporting babel plugins
- [x] eslint and supporting packages
- [x] create `.nvmrc` file for current node version
- [x] update to `node@11.3.0` and current npm
- [x] upgrade to babel 7
- [x] update babelrc
- [x] upgrade to `gulp@4.0.0`
- [x] refactor gulp tasks to use v4 api
- [x] remove/replace `gulp.util` things

Work here will very likely expose new issues with upgraded packages.  Those should all be addressed as part of this issue.  it could be a big chunk of work.

### PR DESCRIPTION
**Pull request by felixscheffer**
Resolves #1137.

I have no idea what I am doing 🙈

### CODE REVIEW

**Comment by felixscheffer** [comment]
I finally managed to break something 😋 

After upgrading gulp, `npm run build` wasn't working anymore.  Running  `npm install --save-dev gulp-babel @babel/core` solved the problem, but now `npm run server` is constantly restarting.

I think it's time for special agent @n8rzz  to take over 😂 😂

**Comment by felixscheffer** [comment]
```
$ npm run coveralls

> openScope@6.7.0-BETA coveralls C:\Dev\openscope
> nyc report -r text-lcov | coveralls


C:\Dev\openscope\node_modules\coveralls\bin\coveralls.js:18
        throw err;
        ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
```

**Comment by felixscheffer** [comment]
`gulp build` is not creating `scripts/client` and `scripts/server` anymore.

**Comment by n8rzz** [comment]
there are some git webhooks issues happening with github at the moment, likely the cause for the coveralls issue for now.

**Comment by n8rzz** [comment]
@openscope/simulator-admins Hey guys, when you have a minute pull this down and see if you run in to any issues.  You _shouldn't_, but if you do call it out and I'll take a look.

**Comment by n8rzz** [comment]
yes, that file must remain.  it guarantees that the *exact* versions installed for me are also installed for you.  without it, you could end up on a dependency that is a few versions ahead of where I'm at and we can run into inconsistencies.  This just helps make things more repeatable.

Try this:
- verify you are using the updated node and npm versions (see `package.json` file)
- pull this branch fresh
- remove `node_modules`
- `npm cache verify`
- `npm install`

With something like this there shouldn't be a diff on that file.  especially if you're checking out the branch for the first time.

**Comment by erikquinn** [comment]
@n8rzz Alright. After those steps, it's down to `+45/-179`, the difference seeming to be `tcomb` being moved up from 3.2.27 --> 3.2.29 when I generated fresh. We can keep the file, but for the reasons mentioned previously, it'd be nice if we could update it only when there's an important reason to do so.

**Comment by n8rzz** [comment]
@erikquinn once this build finishes, this should be good to merge

**Comment by n8rzz** [comment]
@erikquinn @felixscheffer give this one a shot when you have time.  We're jumping from `node@7` all the way to latest `node@11.3.0`.  also jumping to the next major version of babel.

**Comment by felixscheffer** [comment]
I checked out the branch and ran `npm install` 

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@5.6.0
3 info using node@v8.11.4
4 verbose npm-session f9e6beb64b333dbe
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall openscope@6.8.0-BETA
7 info lifecycle openscope@6.8.0-BETA~preinstall: openscope@6.8.0-BETA
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly pacote git manifest for undefined@github:jonschlinkert/micromatch#2.2.0 fetched in 340ms
14 silly fetchPackageMetaData error for git://github.com/gulpjs/gulp.git#6d71a658c61edb3090221579d8f97dbe086ba2ed Command failed: C:\Program Files\Git\mingw64\bin\git.EXE checkout 6d71a658c61edb3090221579d8f97dbe086ba2ed
14 silly fetchPackageMetaData fatal: reference is not a tree: 6d71a658c61edb3090221579d8f97dbe086ba2ed
```

Any idea?

**Comment by erikquinn** [comment]
@felixscheffer I had to update node (v11.3.0) and npm (6.4.0), and then it worked for me.

**Comment by felixscheffer** [comment]
Thanks @erikquinn. You were right. Now it works.

**Pull request merged**
