### PR TITLE
enhancement/1417 - Add/Update RJTT (Tokyo Haneda Int'l)

### LINKED ISSUE #538: Tokyo Haneda (RJTT) Has No Inbound Traffic
There is no inbound traffic for RJTT.  Only departures.

### LINKED ISSUE #1417: Update & Add RJTT (Tokyo Haneda Int'l)
This is to update RJTT and add the airport to the simulation.

### PR DESCRIPTION
**Pull request by JPNite3**
Resolves #1417
Resolves #538

The purpose of this pull request is to add and update airport RJTT (Tokyo Haneda International Airport).

### CODE REVIEW

**Review by Fechulo — CHANGES_REQUESTED** [review]
Heya @JPNite3 Sorry again for the delays with this. Great work so far, for such a complex airport, there's not actually that much to change.

- [x] See comments on the airport guide also
- [x] All colons must be aligned in the fixes section (with the exception of the _fixes)
- [x] Runways should be ordered alphanumerically, so 04/22 and 05/23 should be defined before the others.
- [x] OPPAR3: "_HME140008" should be a fly-over fix for 16L/R
- [x] OPPAR3: OPPAR could be moved from the exitPoints to the body

really solid work with the non-RNAV departures in general, this one in particular gave me PTSD...
image

- [x] ROVE2A/1B/1C: ROVER could be moved from the exitPoints to the body
- [x] ROVE2A/1B/1C: According to my Navigraph charts the transition ending in AGRIS is actually called BRUCE?
- [x] SYE3: Missing restriction for 16L/R departures to cross the 116 radial at or above 6000
- [x] SYE3: The restriction at SYE should be written as `["SYE", "A120+|A150-"]`
- [x] VADAR1: VADAR could be moved from the exitPoints to the body
- [x] VAMOS3: TT501 is a fly-over fix
- [x] VAMOS3: The restriction at VAMOS should be `["VAMOS", "A90+"]`

Unfortunately that's all I have time for for now, but I'll try to take a look at the rest and and get back to you (hopefully before the end of the day)

**Review by Fechulo — CHANGES_REQUESTED** [review]
This airport has far too many procedures oh my lord....

- [ ] BONUS: "_HME096022" should be a fly-over fix
- [ ] DOYLE: "_HME089022" should be a fly-over fix
- [ ] Feel free to ignore this, but I'd personally love to see the coastline as part of the video map, especially given the terrain is complex enough to cause performance issues on my laptop
- [ ] Finally, the airspace is _huge_. I understand from the guide that this is a combination of a few sectors. Is there anyway we could split it in a way that would still make sense and be somewhat realistic? 

Practical review still pending

**Comment by JPNite3** [comment]
> * [ ]  Finally, the airspace is _huge_. I understand from the guide that this is a combination of a few sectors. Is there anyway we could split it in a way that would still make sense and be somewhat realistic?

There are no published sector maps or anything, so I don't know how I would be able to divide it. Aircraft from the Pacific Ocean (East side) seem to be handled by the controller handling Narita (RJAA), but again, it isn't published so I feel like it would make it less realistic if I were to make a guess and split the whole airspace into two.

**Comment by JPNite3** [comment]
> This airport has far too many procedures oh my lord....
> 
> * [x]  BONUS: "_HME096022" should be a fly-over fix
> * [x]  DOYLE: "_HME089022" should be a fly-over fix
> * [ ]  Feel free to ignore this, but I'd personally love to see the coastline as part of the video map, especially given the terrain is complex enough to cause performance issues on my laptop
> * [ ]  Finally, the airspace is _huge_. I understand from the guide that this is a combination of a few sectors. Is there anyway we could split it in a way that would still make sense and be somewhat realistic?
> 
> Practical review still pending

There are no published sector maps or anything, so I don't know how I would be able to divide it. Aircraft from the Pacific Ocean (East side) seem to be handled by the controller handling Narita (RJAA), but again, it isn't published so I feel like it would make it less realistic if I were to make a guess and split the whole airspace into two.

**Comment by Fechulo** [comment]
@JPNite3 The coordinates for AROSA are still incorrect:
image
It should be somewhere in between PEDLA and AVEEY

Regarding the airspace size; given that information about the airspace sectorisation seems to be unavailable, I'm ok with leaving it as is. After testing the airport for a while, I haven't found it to be much of a problem; little to no conflicts arise on the outer parts of the TMA, thanks no doubt to the design of the procedures and the airspace.

**Review by Fechulo — APPROVED** [review]
✔️ Nice job, really cool airport! RJAA next? 😉

**Pull request merged**
