### PR TITLE
feature/1664 - Add KSAT

### LINKED ISSUE #1664: Add KSAT - San Antonio Int'l
Add KSAT.

### PR DESCRIPTION
**Pull request by MichaelDMcCracken**
Resolves #1664 

The purpose of this pull request is to add KSAT - San Antonio Int'l

### CODE REVIEW

**Review by Fechulo — CHANGES_REQUESTED** [review]
Hi @MichaelDMcCracken! Sorry it's taken me this long to take a look at this PR, it's been a hectic few months 😅 Overall, impressive work with KSAT! Only a couple of minor issues and a missing airport guide

- [x] the arrivalRunway, departureRunway & defaultMaps keys should got near the top (before airspace definitions)
- [x] ALAMO3 Departure: Missing GOBBY and HENLY transitions
- [x] ALISS5 Departure: Missing DIANT transition
- [x] BRAUN3 Arrival: Missing WAILN transition
- [x] LEMIG1 Arrival: Missing THX transition
- [x] MARCS1 Arrival: Missing CWK and IDU transitions
- [x] No Airport Guide
- [ ] I noticed there's a some restricted airspace and a number of MOAs in the area. If these are active on a regular basis, they should be included in the file.

**Comment by MichaelDMcCracken** [comment]
> * [ ]  I noticed there's a some restricted airspace and a number of MOAs in the area. If these are active on a regular basis, they should be included in the file.

The restricted airspace is a significant distance outside of the TRACON airspace. And to my knowledge (could be wrong), there isn't a way to differentiate between MOAs and restricted in the airport file.

**Comment by Fechulo** [comment]
@MichaelDMcCracken Correct, there is no way to differentiate between prohibited/restricted/danger areas and MOAs, they're all treated as restricted airspace in, so any relevant MOAs should be included (as long as they're frequently active and don't massively disrupt the flow of traffic. You can re-request a review from me once it's ready

**Comment by MichaelDMcCracken** [comment]
> @MichaelDMcCracken Correct, there is no way to differentiate between prohibited/restricted/danger areas and MOAs, they're all treated as restricted airspace in, so any relevant MOAs should be included (as long as they're frequently active and don't massively disrupt the flow of traffic. You can re-request a review from me once it's ready

@Fechulo 
I looked into the MOAs, but since there isn't a way to define a bottom altitude, it appears that it would significantly disrupt traffic flow. The bottom of the MOAs are near the very upper part of the airspace, which effectively removes a huge chunk of useable space if I can't define a lower limit to the MOA. 

It should be ready for a review, but I don't have the button "Request Review" any more. It just offers me to convert back to draft.

**Comment by Fechulo** [comment]
@MichaelDMcCracken Looks like some of the changes I requested [here](https://github.com/openscope/openscope/pull/1665#pullrequestreview-569979731) haven't been pushed

**Comment by MichaelDMcCracken** [comment]
> @MichaelDMcCracken Looks like some of the changes I requested [here](https://github.com/openscope/openscope/pull/1665#pullrequestreview-569979731) haven't been pushed

No idea what happened there. Should be up to date now.

**Review by Fechulo — APPROVED** [review]

**Pull request merged**
