### PR TITLE
devops/1933 - Add more build information to HTML

### LINKED ISSUE #1933: Improve build information in dev tools
Provide the commit date, hash, and message in the html for easier determination of the build you are testing.

### PR DESCRIPTION
**Pull request by erikquinn**
Resolves #1933.

### CODE REVIEW

**Review by n8rzz — APPROVED** [review]

**Comment by erikquinn** [comment]
Hm, actually this doesn't work quite right. Everything works locally, but when it actually performs the deployment _on heroku_, it fails. The heroku build log says this:
```javascript
       > openscope@6.27.0-BETA build /tmp/build_22b390db
       > gulp build --prod
       
       [16:23:00] Using gulpfile /tmp/build_22b390db/Gulpfile.js
       [16:23:00] Starting 'build'...
       [16:23:00] Starting 'clean'...
       [16:23:00] Starting '<anonymous>'...
       [16:23:00] Finished '<anonymous>' after 4.05 ms
       [16:23:00] Finished 'clean' after 4.96 ms
       [16:23:00] Starting 'build:scripts'...
       [16:23:00] Starting 'build:server'...
       [16:23:00] Starting 'build:styles'...
       [16:23:00] Starting 'markup'...
       [16:23:00] Starting 'buildScripts'...
       [16:23:00] Starting 'buildServer'...
       [16:23:00] Starting 'buildStyles'...
       [16:23:00] Starting 'buildMarkup'...
[16:23:00] 'buildMarkup' errored after 150 ms
[16:23:00] Error: [git-rev-sync] failed to execute command: fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
/undefined
    at _command (/tmp/build_22b390db/node_modules/git-rev-sync/index.js:20:13)
    at Object.date (/tmp/build_22b390db/node_modules/git-rev-sync/index.js:168:19)
    at buildMarkup (/tmp/build_22b390db/tools/tasks/buildMarkup.js:26:33)
    at bound (domain.js:395:14)
    at runBound (domain.js:408:12)
    at asyncRunner (/tmp/build_22b390db/node_modules/async-done/index.js:55:18)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
[16:23:00] 'markup' errored after 152 ms
[16:23:00] 'build' errored after 159 ms
       [16:23:00] The following tasks did not complete: build:scripts, build:server, build:styles, buildScripts, buildServer, buildStyles
       [16:23:00] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openscope@6.27.0-BETA build: `gulp build --prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openscope@6.27.0-BETA build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.9Citx/_logs/2022-03-18T16_23_00_912Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

I guess it's not really cloning the repo, and therefore does not actually have a git repository for `git-rev-sync` to reference. It must just be receiving the current state of the codebase when a commit is pushed, but no actual information about the pushed commit (or other history). Not entirely sure how to go about it.

In the absence of suggestions, I think I'll just give up and close this one.

**Comment by n8rzz** [comment]
Interesting.  I'll take a look at this a little later tonight.

**Comment by n8rzz** [comment]
a quick search of the googles before I get the kids yields this, which may prove useful: https://stackoverflow.com/a/48326313/5129884

**Comment by erikquinn** [comment]
Sounds hopeless! Guess I'll just close it 🤷‍♂️

**Pull request closed without merging**
