### PR TITLE
refactor/586

### LINKED ISSUE #586: CanvasController is misspelled ConvasController

### PR DESCRIPTION
**Pull request by sam-irl**
CanvasController misspelled ConvasController. Fixes #586

### CODE REVIEW

**Comment by erikquinn** [comment]
No way!!!! That's hilarious! How in the _world_ did we never notice? :scream:

**Comment by n8rzz** [comment]
I blame @erikquinn, he's our spelling inspector. But  sure it was my fault for putting it there. The best part is it's probably been there a _long_ time.

**Comment by sam-irl** [comment]
Can confirm that was the only instance, merging

**Comment by sam-irl** [comment]
Apparently I don't have perms to merge, if @erikquinn could handle that please

**Comment by erikquinn** [comment]
@n8rzz :roll_eyes:

**Comment by erikquinn** [comment]
And yes, this was the only reference to it, so we're good to go in that regard.

**Comment by sam-irl** [comment]
👍 I wasn't sure if I should add a refactor to the changelog, thanks

**Comment by erikquinn** [comment]
@sam-irl No problem, I should have done it initially, but didn't. It's actually in another of my PRs that hasn't yet been finished. Now I can sneak it in here! :wink:

**Comment by n8rzz** [comment]
@sam-irl only admins can merge, and that is by design.  So you shouldn't need to worry about doing any merges.

**Pull request merged**
