### PR TITLE
refactor/1428 - KCVG Arrivals Colliding

### LINKED ISSUE #1428: KCVG arrivals colliding
Browser: Google Chrome

Airport: KCVG

Approximate play time before issue: Immediately

#### Issue Description
The arrivals on a few different patterns collide on entry into airspace. For example, the BRUSH3 and GAVNN4 arrivals have aircraft spawn on top of each other.

Suggested fix: Consolidate spawnPatterns on top of eachother into one.

#### Steps to reproduce
- Load KCVG
- Wait for first arrivals to arrive

### PR DESCRIPTION
**Pull request by JPmAn24**
Resolves #1428 

The purpose of this pull request is to adjust/consolidate arrivals so that they don't collide at KCVG

### CODE REVIEW

**Comment by erikquinn** [comment]
Did they actually conflict? Or were they just stacked on top of each other at different altitudes?

**Comment by JPmAn24** [comment]
@erikquinn Yes they did conflict.

**Comment by erikquinn** [comment]
Checking on my phone I show that they are all separated. The only thing that's weird is the way they spawn stacks everywhere at the beginning. And that's only a result of the way the prespawn logic currently works (and will be improved later).

@fechulo it's up to you guys what you want to do, whether it's keeping the low arrivals in there so the tiny aircraft aren't on the big jet arrivals, or removing them so we don't start with stacks everywhere. Just wanted to point out that it isn't exactly a "bug" being fixed here, it's more of an airport design change.

**Comment by Fechulo** [comment]
@erikquinn I guess I just assumed I had originally added conflicting spawnPatterns when I made the airport (something which I did do for a number of airports) and din't bother check what the actual problem is. Apparently I actually made sure the spawnPatterns didn't conflict and, other than the awkward overlapping, a conflict outside controlled airspace shouldn't be possible the way it's currently done. @JPmAn24 If you can show that there is actual separation infringements caused by the current spawnPatterns, then we can merge this. Otherwise, I'd rather keep the old code.

**Comment by erikquinn** [comment]
image

Finally on a real computer 😌

The screenshot is what I see. As I fast forward, they stay at those altitudes of 120 and FL200, so they never do conflict. So it sounds like we'll keep them in the file. When #1427 is addressed, the weird stacks should no longer be a thing.

Closing.

**Comment by JPmAn24** [comment]
@erikquinn Thanks. Now for me to test #1427.

**Pull request closed without merging**
