### PR TITLE
refactor/1525 - Bring back SAME

### LINKED ISSUE #1525: Bring back SAME

### PR DESCRIPTION
**Pull request by Fechulo**
Resolves #1525 

### [Test me here!](https://openscope-dev-pr-1527.herokuapp.com/)

### CODE REVIEW

**Comment by Fechulo** [comment]
I want to test it a little more before merging but it's ready for review

**Comment by Fechulo** [comment]
> I want to test it a little more before merging but it's ready for review

Happy with this one too 😄

**Comment by Fechulo** [comment]
Yeah so there are very minor changes to SAWH and SAEZ, both of which were merged before I found these issues. Since it's still part of the same update, I figured it would be fine to add them to this PR. I can separate them if you'd like.

**Comment by erikquinn** [comment]
Okay, they are real small, so that's fine. Just wanted to double check.

**Pull request merged**
