### PR TITLE
feature/1656 - Add KPHL

### LINKED ISSUE #1656: Add KPHL - Philadelphia Int'l
Opening the issue to claim PHL as my next project.

### PR DESCRIPTION
**Pull request by MichaelDMcCracken**
Resolves #1656 

The purpose of this pull request is to add KPHL.

### CODE REVIEW

**Comment by MichaelDMcCracken** [comment]
@Fechulo 
Only thing I know that is remaining is the multiple airspace support and airport guide. I DID set up the Expect altitudes for those crossing restrictions that would've been assigned by center, just like we did for KGSO in #1655. 

Also, the PHL2 does not have any assigned headings, but I did find a table of the IFR departure headings based on the given departure fix and can confirm that these are accurate based on past experience operating there in real life. The sim seems to break for me when I remove these headings from the exitPoints, so I don't know what solution you guys want.

**Comment by Fechulo** [comment]
@MichaelDMcCracken Oh man I'm excited about this one! I haven't looked at any of the files yet, I'll wait until the airport guide and multiple airspace is all done before starting a full review (I'm quite busy this week anyway).

Regarding the PHL2, I think having the headings in the exitPoints works quite well, so I don't see the need for removing them.

**Comment by MichaelDMcCracken** [comment]
@Fechulo 
> Regarding the PHL2, I think having the headings in the exitPoints works quite well, so I don't see the need for removing them.

That works for me. I just wasn't sure if that was going to be "by the book" since it isn't technically part of the SID. Airspace definitions are updated.

**Comment by MichaelDMcCracken** [comment]
@Fechulo 

Ready for review.

**Review by Fechulo — CHANGES_REQUESTED** [review]
@MichaelDMcCracken Sorry again for the delay on this 😬 Good news is there aren't many changes to be done:

- [x] Wind, arrivalRunway & departureRunway keys should got at the top (before airspace)
- [ ] Airspace needs to be indented correctly
- [ ] PXT is not defined in the fixes section (but used in the PAATS3 arrival)
- [ ] BOJID2 Arrival: Missing some altitude restrictions along the downwind. Add the headings at the end of the STAR
- [ ] JIIMS3 Arrival: Add the headings at the end of the STAR
- [ ] PAATS3 Arrival: Add the headings at the end of the STAR. PXT is not defined in the fixes section
- [ ] SLATT4 Arrival: Should be defined before SPUDS4 arrival
- [ ] SPUDS4 Arrival: Missing some altitude restrictions along the downwind. Add the headings at the end of the STAR
- [ ] Difficulty set to hard but does not meet requirements. An airport needs to have more than 60acph to be considered 'hard' (currently 46). Either change difficulty to medium or increase traffic levels (Philly is a busy airport, we can definitely aim for 60+ here)

Great work!

**Comment by MichaelDMcCracken** [comment]
> * [ ]  JIIMS3 Arrival: Add the headings at the end of the STAR

On my Jepp charts, there isn't a heading assigned after PSOUT and STAYK. They're just fly-over points.

> * [ ]  PAATS3 Arrival: Add the headings at the end of the STAR.

Same for this arrival.

**Comment by Fechulo** [comment]
@MichaelDMcCracken Yeah they don't show up on the actual chart but they do on the textual description
Screenshot 2021-01-17 223902

**Comment by MichaelDMcCracken** [comment]
All issues fixed.

**Review by Fechulo — APPROVED** [review]
Love it ❤️

**Pull request merged**
