### PR TITLE
refactor/545

### LINKED ISSUE #545: scale is cutoff by aircraft strip list
screen shot 2017-06-30 at 6 44 47 am

### PR DESCRIPTION
**Pull request by sam-irl**
The scale was cut off by the (closed) aircraft bar, I increased `const offset` to rectify. Resolves openscope/openscope#545

### CODE REVIEW

**Comment by sam-irl** [comment]
8c57805 either makes it fine or twice as bad. I think it's fine.

**Comment by sam-irl** [comment]
@erikquinn Yep, my bad. I am reinstalling Linux Windows subsystem and `npm install` isn't the fastest, I do usually check my commits

**Comment by sam-irl** [comment]
blocked by #799

**Comment by erikquinn** [comment]
Will be fixed as part of #236 in #799. Closing.

**Pull request closed without merging**
