### PR TITLE
refactor/1286 - Update EDDF to AIRAC 1901

### LINKED ISSUE #1286: Update EDDF to AIRAC 1901
With AIRAC 1810 the SIDs to `RATIM`, `DKB`, `ROTEN` and `NOMBO` were replaced by one universal SID 
that ends at point `AKONI` thereafter aircraft follow airways to get to the old SID exits:

screenshot_199

In addition some STAR designators changed.

### PR DESCRIPTION
**Pull request by Marcel510**
Resolves #1286 

Adds `AKONI` `1A` `1D` `1F` `1L` `1S`
Removes `NOMBO`* `DKB`* `ROTEN`* `RATIM`*
Updates spawnpattern to EDDM

STARs:
ASPAT2E -> ASPAT4E
ASPAT2W -> ASPAT4W
EMPAX2E -> EMPAX3E
EMPAX2W -> EMPAX3W

### CODE REVIEW

**Comment by felixscheffer** [comment]
@Marcel510 I added initial climb altitudes to SIDs in eddf.json in #1282. Can you have a look at it and add the new `altitude` attribute to the new SIDs in this PR? (Feel free to double-check that I added the correct altitudes 😉)

@erikquinn #1282 should be merged before this one.

**Comment by Marcel510** [comment]
@felixscheffer Of course. I'll do that after #1282 is merged.


---

Awaiting #1282

**Comment by erikquinn** [comment]
#1282 merged. Unblocking.

**Comment by Fechulo** [comment]
Practical review still pending

**Comment by Fechulo** [comment]
I'll happily merge this PR without any changes to the spawnPatterns but I'd like to see them updated at some point, so we can either include them here or open up another issue. I'll leave that decision to you.

**Comment by Marcel510** [comment]
@Fechulo My suggestion would be to tweak the spawnpatterns now slightly by increasing the traffic volume by 20-30% and decrease the the values of Lufthansa Cargo. And a complete spawnpattern overhaul at a later time as this PR was intended to update EDDF to the newest AIRAC quickly and not a complete airport overhaul.

**Comment by Fechulo** [comment]
Sounds good to me! Let me know when it's ready for re-review

**Comment by Marcel510** [comment]
@Fechulo forget to update the airport guide

**Pull request merged**
