### PR TITLE
bugfix/1316 Mark deep render when aircraft is (de)selected

### LINKED ISSUE #1316: Mark deep render when aircraft is (de)selected
Playing v6.10 prod.

The compass around the screen does not appear when selecting an aircraft. Instead, i have to scroll to get it to render. Same goes for de-selecting an aircraft.

### PR DESCRIPTION
**Pull request by Mathew-Estafanous**
Resolves #1316

The compass now (dis)appears once the aircraft is (de)selected instead of having the player scroll the mouse wheel for it to initially appear.

### CODE REVIEW

**Comment by Mathew-Estafanous** [comment]
> Since it's being used for both select and de-select, I'd encourage renaming `_onSelectAircraft` to `_onToggleAircraftSelection`. I'd also encourage creating a new event name, `SELECT_AIRCRAFT` should be used for just that, _selecting_ an aircraft and I feel like this is actually different concern.

Thanks for the suggestions. I sent an update with the changes you suggested. Would you say they are more appropriate now?

**Comment by Mathew-Estafanous** [comment]
We could do that but I saw that other methods did the same thing by just instantly calling the _makeDeepRender() method.

**Comment by n8rzz** [comment]
> Can't we actually just do a `trigger(EVENT.MARK_DEEP_RENDER)`? Or is there not an event for that. Seems like that would be much more straightforward, but I'm not sure if it's currently an event. I know we have `EVENT.MARK_DIRTY_CANVAS`, though that may have since been renamed, and I'm not sure if it marked a shallow or deep render.

Triggering that action directly is certainly an option, but I'd argue that is a little bit harder to track.  This way there is a pretty clear line between even triggered, why it was triggered, and resulting callback after event.

**Comment by cake-pie** [comment]
Obsoleted by #1422, see [#1316 (comment)](https://github.com/openscope/openscope/issues/1316#issuecomment-650576877)

**Pull request closed without merging**
