### PR TITLE
refactor/290

### LINKED ISSUE #290: Deprecate fixRadialDist()
and replace with `DynamicPositionModel.generateDynamicPositionFromBearingAndDistance()`

### PR DESCRIPTION
**Pull request by sam-irl**
Turns out that all instances of fixRadialDist() besides those below have been replaced previously. Resolves #290.
image

### CODE REVIEW

**Comment by n8rzz** [comment]
I'd still like for @erikquinn to peak at this just in case. Looks good to me!

**Comment by sam-irl** [comment]
Are only people in the owners group authorised to merge?
image

**Comment by indianbhaji** [comment]
@sam-irl Yes

**Comment by n8rzz** [comment]
Yes.  We have the main branches protected and only admins can merge into them. It gives us control over the code going into the project and allows for consistency in merges (cause there are only two of us with the power)

**Comment by n8rzz** [comment]
It might slow things down a little, but the control and consistency is worth the slowdown.

**Comment by sam-irl** [comment]
@n8rzz sorry, I just saw your comment on #587. just clarifying

**Comment by n8rzz** [comment]
@sam-irl no problem. It's a valid question. It's been a while since we've had someone come in and knock stuff out like you've been doing. So thank you!

**Comment by erikquinn** [comment]
image

@sam-irl Yep, it's based on the team people are in that gives them varying levels of access to doing stuff. We all depend on each others reviews, but only @n8rzz or I can make changes to our protected branches (`develop`, `release/x.x.x`, and `master`) :smile:

**Pull request merged**
