### PR TITLE
bugfix/704

### LINKED ISSUE #704: Command line overlaps with toggle buttons
Browser: All

Airport: n/a

Approximate play time before issue: n/a

#### Issue Description
The command line overlaps with some of the toggle buttons. 

command line

#### Steps to reproduce
- Hold down any key on the command line until the text overlaps with the toggle buttons

### PR DESCRIPTION
**Pull request by n8rzz**
Resolves #704

Adds `footer` section to `index.html` and combines former partials `controls` and `score` with the `#command` input
* updates styles to use flexbox with properly organized children

### CODE REVIEW

**Comment by n8rzz** [comment]
@erikquinn @Fechulo please give this one a close look.  I've complete changed how the footer is structured and may have, inadvertently, broken something.  I haven't seen any breakages, but I'd like to be cautious.

**Comment by n8rzz** [comment]
and that's why we do PRs, good catch!  looks like I'm mathing incorrectly again 🤕

**Comment by n8rzz** [comment]
@Fechulo [finally] had a chance to update this. the issues you mentioned should now be resolved.  please take a look when you have some time.

**Comment by Fechulo** [comment]
Everything works now 😄 but the toggle buttons are still too far to the left (Unless that's desired)

**Comment by erikquinn** [comment]
Oh yeah, that's a little funny lookin.

**Comment by n8rzz** [comment]
You crazy kids and your massive screens.

@Fechulo are you thinking the buttons should butt right up against the score instead of being centered?

**Comment by Fechulo** [comment]
@n8rzz that's the way it was before but they look just fine in the center. I just wanted to make sure it was intended.

**Comment by erikquinn** [comment]
@n8rzz nah, that seems super awkward. Let's slide it right please, yes adjacent to the score would be good.

**Comment by n8rzz** [comment]
I can do that. We have a better DOM structure and we're using flexbox now, so that should be an easy change to make.

**Comment by n8rzz** [comment]
@Fechulo @erikquinn that should do it.  take a peek and let me know what you think!

**Comment by Fechulo** [comment]
Maybe unrelated to this PR, but there's some glitchy stuff going on. When switching between airports, the traffic of the previous airport is not removed and just freeze middair. Also this blue line?
blue line

**Comment by n8rzz** [comment]
ick, I know where that line is coming from and I had no idea that classname was being used there as well 🤕.

I noticed the aircraft not clearing thing too, but that was on my canvas refactor branch and I assumed that was something local.  It seems not.  Hmm, that's a problem.  I'll try to dig into that tonight after the munchkins are sleeping.

**Comment by n8rzz** [comment]
OHHH, I wonder if that has something to do with the `radarTargets` that @erikquinn just implemented?

**Pull request merged**
