### PR TITLE
bugfix/659

### LINKED ISSUE #659: Slight misalignment in airport selection dialog
Browser: All
Airport: N/A

#### Issue Description
Something in openscope/openscope#628 (feature #481) seems to have accidentally undone some minor adjustments to some `airport-list` classes' css, and now there is some slight misalignment as a result. Will need to re-implement those values in the new less files.
image

### PR DESCRIPTION
**Pull request by erikquinn**
Resolves #659 

Fix misalignment in airport selection dialog.

### CODE REVIEW

**Comment by sam-irl** [comment]
I think you mean #659, ftfy

**Comment by erikquinn** [comment]
@sam-irl GAH! those damn zube card numbers strike again :disappointed:

Thanks.

**Comment by erikquinn** [comment]
@erikquinn re-open this under the _correct branch name_, you fool

**Comment by erikquinn** [comment]
Reaplced by #673. Closing.

**Pull request closed without merging**
