### PR TITLE
feature/541

### LINKED ISSUE #541: New Airport: KATL (Hartsfield–Jackson Atlanta Int'l)
Hartsfield–Jackson Atlanta International Airport (IATA: ATL, ICAO: KATL, FAA LID: ATL), also known as Atlanta Airport, Hartsfield, or Hartsfield–Jackson, is an international airport located 7 miles (11 km) south of Atlanta's central business district, in the U.S. state of Georgia. It has been the world's busiest airport by passenger traffic since 1998; and by number of landings and take-offs from 2005 to 2013, losing that title to Chicago-O'Hare in 2014, but regaining it a year later. Hartsfield–Jackson held its ranking as the world's busiest airport in 2012, both in passengers and number of flights, by accommodating 100 million passengers (more than 260,000 passengers daily) and 950,119 flights. Many of the nearly one million flights are domestic flights from within the United States, where the airport serves as a major hub for travel throughout the southeastern region of the country. The airport has 207 domestic and international gates.

Taken from Wikipedia

### PR DESCRIPTION
**Pull request by Fechulo**
Resolves #541.

Add KATL.

---

According to Wikipedia, the airport has 898,356 yearly operations. Traffic level should fall between 102.6acph and 307.7acph. Currently, there's a total of 103acph. 👍

### CODE REVIEW

**Comment by erikquinn** [comment]
> Traffic level should fall between 102.6acph and 307.7acph. Currently, there's a total of 103acph.

this stat gives so many emotions.... :laughing: :grimacing: :cry: :joy: :scream:

**Comment by Fechulo** [comment]
It's insanely busy!

**Comment by n8rzz** [comment]
well it is a major hub for how many airlines?  I'd believe it.

**Comment by erikquinn** [comment]
> well it is a major hub for how many airlines? I'd believe it.

maybe, but more than anything it's the Delta show... I think they have like almost two thirds of the airport. Nuts.

**Comment by Fechulo** [comment]
> the file is too large for git to render, and so it won't allow me to provide a line-by-line review.
> So instead, I'll have to list the items out here.

This is sad...

All SID's should be fixed now!

**Comment by Fechulo** [comment]
> PECHY1: this is undoubtedly pronounced "Peachy One". Georgia peaches... they're like a thing.

Good to know! This is what I love/hate about American airports. I know that a lot of the fixes are named after specific things that have to do with the area, but I just never know what those things are.

> PECHY1: last two fixes on the 27s are in reference to the wrong runways

Fixed 👍

> RMG5, SINCA6: sort entries alphabetically

Fixed 👍

> Really ought to go to bed

Me too! ⌚️ 👀

**Comment by Fechulo** [comment]
> WHINZ4: VICTU has altitude restriction of A40+

Done 👍

**Comment by Fechulo** [comment]
I forgot to declare DLLNN 😬

**Comment by Fechulo** [comment]
Now, done 😅

**Pull request merged**
