### PR TITLE
Add "Commands" menu button

### LINKED ISSUE #1568: Add link in help menu to command reference

### PR DESCRIPTION
**Pull request by N864T**
Resolves #1568 

The purpose of this pull request is to add a menu button to open the command reference.

### CODE REVIEW

**Comment by N864T** [comment]
Sorry! Git's doin' some weird things!

**Comment by N864T** [comment]
Hmmm... My "fix" doesn't seem to have succeeded. Again, sorry any of this happened.

**Comment by erikquinn** [comment]
@N864T Ah! Actually those were me making small adjustments and adding a changelog entry, I just forgot to hit the green merge button because I was waiting on the tests to finish running on it, so it was good to go. I should be able to undo all of the undos though, so don't worry :)

**Comment by N864T** [comment]
Thanks Erik!

**Pull request merged**
