### PR TITLE
feature/1870 — Add Nashville Intl (BNA)

### LINKED ISSUE #1870: Add BNA (Nashville Intl)
Add BNA.

### PR DESCRIPTION
**Pull request by MichaelDMcCracken**
Resolves #1870 

The purpose of this pull request is to add KBNA.

### CODE REVIEW

**Comment by MichaelDMcCracken** [comment]
@openscope/airport-reviewers @Fechulo 

Ready for review.

**Comment by erikquinn** [comment]
> @openscope/airport-reviewers @Fechulo
> 
> Ready for review.

Then please _request_ the review, up at the top right. I'll do it for you.

**Comment by MichaelDMcCracken** [comment]
> > @openscope/airport-reviewers @Fechulo
> > Ready for review.
> 
> Then please _request_ the review, up at the top right. I'll do it for you.

Apologies, I thought for sure I had also clicked it.

**Review by Fechulo — CHANGES_REQUESTED** [review]
2 very small changes. I love the overflights!

**Review by Fechulo — APPROVED** [review]
:shipit:

**Pull request merged**
