### PR TITLE
enhancement/1472 - Update airport terrain files to contain water polygons

### LINKED ISSUE #1472: Update airport terrain files to contain water polygons
Now that #420 has been completed, all the existing aiport terrain files should be updated to contain the water polygons (where applicable)

### PR DESCRIPTION
**Pull request by oobayly**
Resolves #1472

Now that #420 has been completed, all the existing aiport terrain files should be updated to contain the water polygons (where applicable).

Where video maps contain coastline data, the water polygons mirror those lines.

This modifes the terrain for the following airports:
* CYHZ
* CYOW
* EDDH
* EGCC
* EGGW
* KATL
* KBOS
* KDCA
* KLAS
* KMIA
* KSEA
* KSFO
* LSZH
* LTBA
* OMAA
* OMDB
* OTHH

### CODE REVIEW

**Comment by oobayly** [comment]
> Runway 32 at Boston Logan and most of Doha airport seem to be completely submerged, we should consider moving some of those points bring them back above the water.

Well spotted. I'll use OSM to adjust the boundary. The reason is that the shapefiles are quite coarse*, especially where you have artifically made coast lines like those two airports. I image places like Hong Kong Intl would do the same.

\* I've used the high resolution GSHHG shapefiles as the fine resolution ones appear _"bumpy"_ so there's little benefit in using them
image

> I notice some airports show rivers and others don't, e.g, Ottawa vs Portland.

Yes, I noticed that too. For example, I manually altered KDCA as the videomap contained obvious coastlines, even though the GSHHG coastline stopped short. As Portland didn't have any obvious coastlines I didn't know to add any. 
The reason is that GSHHG data contains the Ottowa River in the L2 (lakes) shapefiles, but for the Columbia River they're not. There must be a certain threshold that NASA use, or it's because Ottowa River is connected directoly to Lake Ontario. There is also a river database, but those are only 1d so can't be turned into polygons.

Major rivers could be added manually using OSM, but it raises the question about what threshold size we should use (rather than delgating that decision to NASA :grin:)

**Comment by oobayly** [comment]
As a test, I've added the Rhine to EDDL. It's not too hard to do it's just a matter of buffering the river outlines to the correct size. If we work on the basis that we only use rivers classified as "Permament Major Rivers", then some there's some consistency for whether rivers are shown.

image

**Comment by Fechulo** [comment]
@oobayly Do you want to keep the Rhein in the EDDL map and add it to the PR? I think it looks great. At the end of the day it'll be a pretty subjective decision whether or not a river should be added. Is the process for adding water and rivers to the terrain files clearly documented?

**Comment by oobayly** [comment]
> Do you want to keep the Rhein in the EDDL map and add it to the PR?

I wanted to make sure you're happy with the river. I'll go back and generate rivers for any other airports that might contain them. If it's going to be done, it might as well be complete...

> Is the process for adding water and rivers to the terrain files clearly documented?

I used the [qgsopenscope plugin](https://github.com/openscope/qgsopenscope) that I wrote to generate the water and terrain files. It basically automates the process in the [Terrain Generation documentation](https://github.com/openscope/openscope/blob/develop/documentation/airport-terrain-generation.md).
The readme file explains how to install it and use it, as well as having links to the two YouTube videos:
* [qgsopenscope](https://github.com/openscope/qgsopenscope)
* [Installing and using the QgsOpenScope plugin for QGIS](https://www.youtube.com/watch?v=V0A83VNzLCU)
* [Reshaping water polygons to match the video map](https://youtu.be/5-rSBTLS3kA)

I can update the Terrain Generation docs to include the usage of the plugin (although if you're wanting a description of how the manual process is done, then it might take a bit more time), as well as document the process of buffering lines to generate river polygons (it's a more manual process).

**Comment by Fechulo** [comment]
Some documentation on rivers would be great, even if it's just a video showing the process for one of the airports. I know using words to explain a manual process like this can be quite difficult.

**Comment by erikquinn** [comment]
https://github.com/openscope/openscope/pull/1473#issuecomment-554351102

^ good stuff. Do we have all of these references also included in this repository's documentation somewhere? That's usually where we go looking for documentation, so even just a simple "go look over there" would be sufficient. Just don't want to lose the good info in the above post when we merge this pr and forget about the comments :)

**Comment by oobayly** [comment]
> Do we have all of these references also included in this repository's documentation somewhere?

We all love doing documentation, don't we! I'll get around to adding ~~annotations~~ subtitles to the 3rd video (my headset mic is :hankey:)

**Pull request merged**
