### PR TITLE
feature/1033 - overflights

### LINKED ISSUE #1033: Add support for overflight spawn patterns
Currently, it's an expectation that every aircraft that enters the airspace must land within the airspace. But sometimes there are overflights!

The work that will need to be done for this will _really_ pave the way to enable landing multiple airports, because it will remove all the assumptions that the airplane will land at the loaded "airport". If that's no longer expected, and they can choose to not land at all, we should be able to (in theory) add spawn patterns to different airports and it will not self destruct nearly as hard as it would right now.

Inspired by #937.

### PR DESCRIPTION
**Pull request by erikquinn**
Resolves #1033.

Add support for overflights.

## https://openscope-dev-pr-1037.herokuapp.com/

### CODE REVIEW

**Comment by felixscheffer** [comment]
@erikquinn What's the state of this PR? Is there anything left to do?

**Comment by erikquinn** [comment]
I think it's actually done? Could use some documentation probably, but otherwise undo the ksea changes and :shipit:

**Comment by felixscheffer** [comment]
I merged the latest develop branch and put the KSEA arrivals back in (and kept the overflights).

Right now, there are 5 failing tests. At least 3 of them because `DEPARTURE_AIRCRAFT_INIT_PROPS_MOCK ` returns true for `isArrival()` .

**Comment by n8rzz** [comment]
@felixscheffer I'm sure you saw this already, but the actual response in those tests state that the aircraft is already airborne.  You may want to verify that the `DEFAULT_AIRCRAFT_INIT_PROPS_MOCK` is set up correctly for an on-the-ground-departure.  It _should_ be, but I know some of the logic has changed recently with `.isArrival()`/`.isDeparture`.

You can verify this in the `AircraftModel` tests.  Ava supports running a single test file by passing including the path to a directory or path after the test command.  `npm run test -- test/aircraft/AircraftModel` (or whatever the path actually is).

I'm sure you know all this already, just calling it out in case you don't already know  :wink.

**Comment by felixscheffer** [comment]
I finally fixed the tests. 

@erikquinn  @n8rzz Let me know if you are happy with the new tests for `isArrival()` and `isDeparture()`.

@Marcel510 Feel free to test :wink:

**Pull request merged**
