### PR TITLE
feature/1017 - Add more GA aircraft

### LINKED ISSUE #1017: Add more GA aircraft
I have noticed a few aircraft are missing when it comes to GA. I will be adding in a few more aircraft that will give more slow GA than the generic BE36 and cessnas that we currently have.

### PR DESCRIPTION
**Pull request by clscott42**
Resolves #1017.

Add more GA aircraft.

### CODE REVIEW

**Comment by JPmAn24** [comment]
Got it. Taking over.

**Comment by erikquinn** [comment]
@jpman24 do you have a specific goal in mind here? This seems like one that is very open ended and could go on forever since there's no shortage of GA aircraft that exist. If we can get a few done and approved in the next three days, we can get this into the next version, and then deal with any additional aircraft when we get around to it

**Comment by JPmAn24** [comment]
@erikquinn I plan on also adding possibly a HondaJet, and also the Grumman Traveller, then we could merge this and move on to other things.

**Comment by erikquinn** [comment]
Okay, try to get it done by Saturday and it can be merged by Sunday before the cutoff. :)

**Comment by erikquinn** [comment]
And when it's ready, remember to request the review so I don't miss it.

**Pull request merged**
