### PR TITLE
enhancement/1771 - Change Thomas Cook to Sunclass Airlines

### LINKED ISSUE #1771: Update Thomas Cook  Airlines Scandinavia to Sunclass Airlines
In 2019 Thomas Cook Airlines Scandinavia became Sunclass Airlines.

Update the airline information and double check the fleet. Also update any airports as needed, after double checking that the airline still flies there.
[https://en.wikipedia.org/wiki/Sunclass_Airlines](https://en.wikipedia.org/wiki/Sunclass_Airlines)

Needed for ESSA Stockholm/Arlanda, issue #1695 and pull request #1696

### PR DESCRIPTION
**Pull request by OlaRune**
Resolves #1771 

The purpose of this pull request is to change Thomas Cook Scandinavia to Sunclass Airlines.

### CODE REVIEW

**Comment by OlaRune** [comment]
Super small pull request. Just one question, was it correct to tag this as an enhancement? Didn't really feel like it fit any of the categories in [git-flow-process.md](https://github.com/openscope/openscope/blob/develop/documentation/git-flow-process.md)

**Review by indianbhaji — APPROVED** [review]

**Comment by indianbhaji** [comment]
> Super small pull request. Just one question, was it correct to tag this as an enhancement? Didn't really feel like it fit any of the categories in [git-flow-process.md](https://github.com/openscope/openscope/blob/develop/documentation/git-flow-process.md)

I personally think it fits better under refactor, but @erikquinn might have a better opinion on this :)

**Comment by erikquinn** [comment]
Yeah, generally we've said enhancement would take an existing thing and make it "way better". Small corrections here and there we've called refactors instead.

**Comment by OlaRune** [comment]
> Yeah, generally we've said enhancement would take an existing thing and make it "way better". Small corrections here and there we've called refactors instead.

All right, I'll use that next time!

**Pull request merged**
