### PR TITLE
devops/598 - Add lint to travis after-success task list

### LINKED ISSUE #598: Add lint to pull request status checks
image

To the degree possible, it would be nice if we could have something that ensures no pull request adds more hits on our eslint rules. That should help limit the work needed when we eventually come back around and comb through all the files resolving those errors.

### PR DESCRIPTION
**Pull request by erikquinn**
Resolves #598.

Awaiting the build results on this PR to see if it worked.... 👀

### CODE REVIEW

**Comment by erikquinn** [comment]
Looks like there's more to it than that (as I suspected...)

Anybody is free to take this one if they know how to get it done, as that is about as far as I could venture to guess... ☹️

**Comment by n8rzz** [comment]
Some of these lint issues are going to involve a bit o work.  Callouts related to the global `prop` object might be tricky to deal with.

**Comment by cake-pie** [comment]
Not that I've any actual experience using either of these, but they look useful.

[lint-diff](https://www.npmjs.com/package/lint-diff) appears to support linting only changed lines, which is great
[ESLint Changes](https://www.npmjs.com/package/eslint-changes) appears to lint entire changed files; not as ideal, but it does add a nice github status

**Comment by erikquinn** [comment]
lint-diff sounds like a winner! Would still need to figure out how to add it as a status check for PRs, but would actually be better than a straight `eslint` because then we don't have to fully de-lint before starting to use it!

**Comment by felixscheffer** [comment]
@erikquinn  @cake-pie so who wants to take this one over? 😉

**Comment by erikquinn** [comment]
It's beyond my expertise (to say the least), but it may require some sort of admin permissions, so if somebody can tell me what to do, that would also work 😃

**Comment by n8rzz** [comment]
eslint-changes seems pretty straightfoward.  Pretty sure we already have the env var set, so it's just a matter of adding the script block in the `.travis.yml` file.  At least, thats what it looks like to me at first glance.

**Comment by cake-pie** [comment]
> beyond my expertise

Likewise, but I'm not averse to giving it a shot.

**Comment by cake-pie** [comment]
:rotating_light: DO NOT MERGE :rotating_light: contains code changes to test `lint-diff`.

Got it working locally: manually specifying the commit range will indeed filter linter output to include only changed lines. But `$TRAVIS_COMMIT_RANGE` isn't quite doing what we want:

https://travis-ci.org/openscope/openscope/jobs/502952450#L2017-L2020
```
$ npm run lint-diff -- $TRAVIS_COMMIT_RANGE

> openscope@6.12.0-BETA lint-diff /home/travis/build/openscope/openscope
> lint-diff "e21136872861...6cd67fc38c61"
```

That's only the last commit, we want to test the whole PR.

**Comment by cake-pie** [comment]
Success!

lintdiff

I turned PR builds back on, and then limited push builds to trigger only for `develop` and `master`, so we won't have [doubled builds](https://docs.travis-ci.com/user/pull-requests/#double-builds-on-pull-requests).

Since running lint in both test jobs (Node.js 10 / 11) is redundant, I moved linting to its own job that runs independently from the tests (and in parallel with them). I've set it up so that PRs it runs `lint-diff`, and when pushing to master it runs a full `eslint`. Lint jobs are allowed to fail, i.e. lint errors won't make Travis unhappy.

If everyone is ok with this arrangement we can revert e211368 and merge these changes as a first step, so we at least have linting. Still have to click through to Travis to see how it went, though.

Re: adding the status check, I [made some modifications to lint-diff](https://github.com/cake-pie/lint-diff/tree/openscope) but it's completely untested yolo-code at the moment.

**Comment by erikquinn** [comment]
@cake-pie Removed that commit as requested! This will do the trick for now. If you stumble across a way to get it into the GitHub Status Checks, definitely advise, as that would be the ultimate solution here 😃 

Thank you for this!

**Comment by erikquinn** [comment]
@cake-pie Is this still a `DO-NOT-MERGE`, or is it okay to go in?

**Comment by cake-pie** [comment]
Fixed the changelog entry.
Also, prevent coveralls running in `after_success` of lint jobs (leads to [error](https://travis-ci.org/openscope/openscope/jobs/504048896#L536)).
Cleared for merge. :tada:

Whoever has access to coveralls settings -- please [make coveralls bot shut up](https://github.com/lemurheavy/coveralls-public/issues/93#issuecomment-25119377) or it could get spammy -- we don't need it to comment twice (due to two jobs per build) every time there is a change in coverage. The status check should suffice.

I think I'm close to a solution for adding a status check, hopefully will be able to figure it out over the weekend.

**Comment by n8rzz** [comment]
Coveralls comments turned off, so we should be good to go!

**Pull request merged**
