### PR TITLE
Creates ARFF for emergency simulation

### LINKED ISSUE #1554: Add EMERGENCY aircraft to the mix
Hello everyone! I LOVE openscope, however, it lacks one feature that I think would take it to the next level! I suggest adding emergencies where randomized aircraft declare emergencies and then you must vector them back to land- if you can't do it in time, they crash or have to ditch. At the same time, maybe we could start communicating with the ARFF units responding to an emergency. I really don't know where to start though, so if someone could help with this that would be great.

### PR DESCRIPTION
**Pull request by Hawaiicoder**
A small step in issue #1554

The purpose of this pull request is to create an ARFF vehicle for emergency aircraft.

### CODE REVIEW

**Comment by Hawaiicoder** [comment]
I don't want to be pushy but when can this be merged?

**Comment by Hawaiicoder** [comment]
This is certainly because I am new to coding, however, I cannot tell what the reason for the build fail is... is it my fault? And if so, how do I fix it?

**Comment by n8rzz** [comment]
The build is failing because the `JSON` file is invalid, there is a syntax error in there somewhere. (https://travis-ci.com/github/openscope/openscope/jobs/315435308).  The build output may give you a hint as to where, otherwise you could run that file through a JSON linter (google that) or add a json linter to your editor.

**Comment by Hawaiicoder** [comment]
Thank you so much! I'll certainly look into that.

**Comment by Hawaiicoder** [comment]
Okay, I ran it through the JSON Linter at https://jsonlint.com/, but I cannot figure out how to correct it. Again, I am very new to this.

**Comment by n8rzz** [comment]
no worries, we were all _'new to this at one time'_.  You have a few characters in the wrong place is all.  this is what you have submitted with the errors resolved:
```json
{
	"name": "Aircraft Rescue and Firefighting ",
	"icao": "ARFF",
	"engines": {
		"number": 1,
		"type": "P"
	},
	"weightClass": "S",
	"ceiling": 0,
	"rate": {
		"climb": 0,
		"descent": 0,
		"accelerate": 50,
		"decelerate": 35

	},
	"speed": {
		"min": 0,
		"cruise": 50,
		"cruiseM": 0.07,
		"max": 320,
		"maxM": null
	},
	"capability": {
		"ils": false,
		"fix": false
	}
}
```

**Comment by Hawaiicoder** [comment]
Finally finished!

**Pull request closed without merging**
