### PR TITLE
devops/526 - Add typescript support

### LINKED ISSUE #526: Add Typescript support
Use typescript compiler and `tsify` to produce similar `bundle.js` and `bundle.js.map` files during build process

This issue does not cover a complete conversion.  This is just the first step to an eventual complete conversion to typescript

### PR DESCRIPTION
**Pull request by n8rzz**
Resolves openscope/openscope#526 
depends on openscope/openscope#1137 

Switches over to Typescript and updates build pipeline to use `tsify`

- [ ] Enable typescript for tests
- [ ] Testing

### CODE REVIEW

**Comment by erikquinn** [comment]
@n8rzz @felixscheffer What's the status of this? Is it planned to continue, or is it a no-go?

**Comment by felixscheffer** [comment]
I dont know what's the status of this. It's @n8rzz's baby but it would be awesome if we could switch to typescript.

**Comment by n8rzz** [comment]
Very stalled.

This is the closest I've been able to get with it, but it's still miles away from actually working correctly.  I would really love to make this a thing someday, but I fear it will take a very large amount of work to accomplish (a la 2016 refactor).

**Comment by n8rzz** [comment]
My plan for this was to get just enough TS working so that we could use the compiler to do our transpiling while still allowing us to use existing es6 while we slowly convert everything to TS.  I'm not sure that is possible in our case.  Or, if it is, I haven't had any luck making that happen.  

I think the path forward here may be to convert everything all at once with loose compiler settings.  Problem with doing it all at once is where do you start?  If you start at `index.js` and work your way down, you very quickly end up making a ton of changes just to get the compiler building things.

**Comment by felixscheffer** [comment]
I fixed the imports and the sim is loading again but now the tests are broken.

**Comment by n8rzz** [comment]
Review app is building now

**Comment by felixscheffer** [comment]
@n8rzz Looks like we have to fix the tests first...could you have a look?

**Comment by n8rzz** [comment]
@felixscheffer Looks like the tests need the same path updates for lodash imports.  I've been swamped at work so I barely had a chance to look at this, but that is my first impression.  Ava should be able to work with TS without too much extra configuration, be we'll see what happens once those imports are updated.

**Comment by erikquinn** [comment]
Closing I guess. Can always reopen!

**Pull request closed without merging**
