### PR TITLE
enhancement/1882 - Add Embraer 175

### LINKED ISSUE #1882: Change Horizon Air E170 -> E175

### LINKED ISSUE #1884: Add E175 Varient of Aircraft

### PR DESCRIPTION
**Pull request by Flyboy31**
Changed the ICAO code of E170 to E175 as Horizon Air operates the the E175 version of the Embraer aircraft

Resolves #1882.
Resolves #1884.

The purpose of this pull request is to change the Horizon Air E170 ICAO to E175

### CODE REVIEW

**Comment by Flyboy31** [comment]
I've added the E175 varient of the Embraer for future work.

**Review by Fechulo — CHANGES_REQUESTED** [review]
As far as I can tell, E175 is not an ICAO aircraft type identifier. If we're to go by the FAA's list of aircraft identifiers, E75S and E75L are the correct codes. Not sure which one of these is operated by Horizon
image

**Comment by Flyboy31** [comment]
> As far as I can tell, E175 is not an ICAO aircraft type identifier. If we're to go by the FAA's list of aircraft identifiers, E75S and E75L are the correct codes. Not sure which one of these is operated by Horizon
> image
> 

It's the E75L. I'll change it.

**Review by Fechulo — APPROVED** [review]

**Comment by Flyboy31** [comment]
Added E75S varient for review. Once accepted, ready to push to develop branch.

**Review by Fechulo — APPROVED** [review]

**Comment by erikquinn** [comment]
@Flyboy31 Once you're done with it and think it's ready to merge, please remember to remove the "WIP" label, and request a review by the appropriate team (which you've done). 👍

**Pull request merged**
