### PR TITLE
bugfix/1446 - Normalise aircraft heading in "say heading" read-back

### LINKED ISSUE #1446: Normalise aircraft heading in "say heading" read-back
Browser:
All

Airport:
All (Use EGGW for an example)

Approximate play time before issue:
Immediate

#### Issue Description
When issuing the "say heading" command, the heading isn't normalised and may be given as a negative number.

#### Steps to reproduce
When an aircraft on the ABBOT2B STAR enters the airspace, request a heading read-back. The heading will be given as a negative number.

### PR DESCRIPTION
**Pull request by oobayly**
Resolves #1446 

The purpose of this pull request is to ensure that heading returned by the `runSayHeading` and `runSayAssignedHeading` read-backs are normalised to 0° and 360°

### CODE REVIEW

**Comment by oobayly** [comment]
Yeah, I had a look to see if there were test that needed modifying, but there are no AircraftCommander tests (to get some hints from), nor any AircraftController (upon which the AircraftCommander relies) tests.

I was going to say that the tests for degrees_normalize _should_ catch errors, but I've just seen that there are none of those either (proving the assumptions adage!)

**Comment by n8rzz** [comment]
> Yeah, I had a look to see if there were test that needed modifying, but there are no AircraftCommander tests (to get some hints from), nor any AircraftController (upon which the AircraftCommander relies) tests.
> 
> I was going to say that the tests for degrees_normalize _should_ catch errors, but I've just seen that there are none of those either (proving the assumptions adage!)

I was afraid of that.  We use `ava` for testing, which is node based and *does not have a DOM*.  At least, not without a bunch of work.  Because we don't have a DOM within our test env, pretty much anything that imports jquery is not testable.  So that's likely the reason this isn't tested at the moment.

**Comment by oobayly** [comment]
Um, I think we've got our PRs mixed up. The input focus & jQuery one is #1445 

I've cobbed together some test for this one, but am concerned that a badly written test is worse than none at all. `runSayAssignedHeading` relies up the aircaft mcp being set which is currently beyond my comprehension.

```js
import ava from 'ava';
import AircraftCommander from '../../src/assets/scripts/client/aircraft/AircraftCommander';
import AircraftModel from '../../src/assets/scripts/client/aircraft/AircraftModel';
import {
    AIRCRAFT_MOCK_WITH_HEADING,
    AIRCRAFT_MOCK_WITH_HEADING_NEGATIVE,
    RUN_SAY_HEADING_RESULT
} from './_mocks/aircraftCommanderMocks';

ava('.runSayHeading() returns correct when heading is normalized', (t) => {
    const commander = new AircraftCommander();
    const aircraft = new AircraftModel(AIRCRAFT_MOCK_WITH_HEADING);
    const result = commander.runSayHeading(aircraft);

    t.deepEqual(result, RUN_SAY_HEADING_RESULT);
});

ava('.runSayHeading() returns correct when heading is negative', (t) => {
    const commander = new AircraftCommander();
    const aircraft = new AircraftModel(AIRCRAFT_MOCK_WITH_HEADING_NEGATIVE);
    const result = commander.runSayHeading(aircraft);

    t.deepEqual(result, RUN_SAY_HEADING_RESULT);
});
```

**Comment by n8rzz** [comment]
Ha, I tend to take the other side of that coin; any test is better than no test.  Of course, any in this case would typically mean simple happy path test.

I think your example looks good for happy path, I wouldn't have any concerns adding that in.

**Comment by oobayly** [comment]
Started to write my own getRadioHeading method, and then realised that if the "fly heading" command reads back correctly, then I should probably use that!

**Pull request merged**
