### PR TITLE
refactor/481

### LINKED ISSUE #481: Add LESS and reorganize CSS
- add css preprocessor that gives us variables and sane imports
- organize css in an object-oriented manner (base, helpers, landmark, modules)

### PR DESCRIPTION
**Pull request by n8rzz**
Resolves #481 

Adds LESS preprocessor and adds CSS folder structure

### CODE REVIEW

**Comment by n8rzz** [comment]
blocked by #631

**Comment by erikquinn** [comment]
#631 resolved. Unblocking.

**Comment by n8rzz** [comment]
@erikquinn there is so much more I can do with this.  I don't want to go overboard with changes here, though.  So I'm going to call it good with what is included.  more issues will follow after #657 and #141

**Comment by erikquinn** [comment]
@n8rzz are we able to import colors from themes somehow? Or does less only provide the ability to declare variables locally in that file?

**Comment by n8rzz** [comment]
we are able to do that yes.  there are just a few vars already setup here: https://github.com/openscope/openscope/pull/628/files#diff-7f15584447364488474b0cc528a1cc95.  but we can easily add more files for theme vars and such.

**Pull request merged**
